apiVersion: v1
kind: Namespace
metadata:
  name: database
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: database
  name: database-deployment
  labels:
    app: db-postgresql
spec:
  minReadySeconds: 2
  selector:
    matchLabels:
      app: db-postgresql
  replicas: 1
  template:
    metadata:
      labels:
        app: db-postgresql
    spec:
      containers:
      - name: db-postgresql
        image: postgres:15-alpine3.17
        imagePullPolicy: Always
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          value: odoo
        - name: POSTGRES_PASSWORD
          value: odoo
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        - name: POSTGRES_HOST_AUTH_METHOD
          value: trust
        - name: POSTGRES_INITDB_ARGS
          value: --auth-host=md5 --auth-local=trust
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgresql-data
        persistentVolumeClaim:
          claimName: postgresql-data
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: database
  name: postgresql-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---

apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: database
  name: postgresql-data-pv
spec:
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /mnt/data/postgresql-data


---

apiVersion: v1
kind: Service
metadata:
  namespace: database
  name: db-postgresql-service
spec:
  selector:
    app: db-postgresql
  ports:
  - name: db-postgresql
    port: 5432
    targetPort: 5432
  type: ClusterIP
