apiVersion: v1
kind: Namespace
metadata:
  name: odoo

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: odoo
  name: odoo
  labels:
    app: odoo
spec:
  minReadySeconds: 2
  selector:
    matchLabels:
      app: odoo
  replicas: 2
  template:
    metadata:
      labels:
        app: odoo
    spec:
      containers:
      - name: odoo
        image: bitnami/odoo:latest
        ports:
        - containerPort: 8069
        env:
        - name: ODOO_DATABASE_HOST
          value: db-postgresql-service
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        - name: ODOO_DATABASE_ADMIN_USER
          value: odoo
        - name: ODOO_DATABASE_ADMIN_PASSWORD
          value: odoo
        volumeMounts:
        - name: odoo-data
          mountPath: /bitnami/odoo
      volumes:
      - name: odoo-data
        persistentVolumeClaim:
          claimName: odoo-data-pvc

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: odoo
  name: odoo-data-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: odoo-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadWriteOnce
  hostPath:
    path: /mnt/odoo-data

---
apiVersion: v1
kind: Service
metadata:
  namespace: odoo
  name: odoo-service
spec:
  selector:
    app: odoo
  ports:
  - port: 8069
    targetPort: 8069
  type: LoadBalancer

